config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'mypage', to: 'users#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :artists do
    collection do
      get :favorites
    end
    resources :members, only: [:index, :destroy]
    member do
      post 'toggle_favorite'
    end
  end
  resources :live_schedules do
    resources :venues, only: [:new, :create]
  end
  resources :live_records do
    get 'details', on: :member, format: :json
    resources :venues, only: [:new, :create]
  end
  resources :goods do
    resources :categories, only: [:new, :create]
  end
  get 'statistics', to: 'statistics#index'
  root 'home#index'
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :user
  has_many :members, dependent: :destroy
  has_many :live_records, dependent: :nullify
  has_many :live_schedules, dependent: :nullify
  has_many :goods, dependent: :nullify
  accepts_nested_attributes_for :members, allow_destroy: true, reject_if: :all_blank
  mount_uploader :image, AvatarUploader
  validates :name, presence: true, length: { maximum: 25 }
  validates :nickname, length: { maximum: 10 }
  validate :nickname_required_if_mode_on
  validate :founding_date_not_in_future
  validate :first_show_date_after_founding_date
  validate :first_show_date_not_in_future

  def display_name
    nickname_mode && nickname.present? ? nickname : name
  end

  def non_display_name
    nickname_mode && nickname.present? ? name : nickname
  end

  def combined_name
    return display_name if non_display_name.blank?

    "#{display_name}(#{non_display_name})"
  end

  private

  def nickname_required_if_mode_on
    return unless nickname_mode && nickname.blank?

    errors.add(:nickname, "ニックネームモードが有効の場合、ニックネームは必須です")
  end

  def founding_date_not_in_future
    return unless founding_date && founding_date > Time.zone.today

    errors.add(:founding_date, "結成日は今日より前に設定してください")
  end

  def first_show_date_after_founding_date
    return unless founding_date && first_show_date && first_show_date < founding_date

    errors.add(:first_show_date, "初めて見た日は結成日より前に設定することはできません")
  end

  def first_show_date_not_in_future
    return unless first_show_date && first_show_date > Time.zone.today

    errors.add(:first_show_date, "初めて見た日は今日より前に設定してください")
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artist, only: [:show, :edit, :update, :destroy, :toggle_favorite]

  def index
    @artists = current_user.artists
  end

  def show
    @display_attributes = {
      "アーティスト名" => @artist.name,
      "ニックネーム" => @artist.nickname,
      "ジャンル" => @artist.genre,
      "結成日" => @artist.founding_date,
      "初ライブ日" => @artist.first_show_date,
      "メモ" => @artist.memo
    }.select { |_, value| value.present? }
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = current_user.artists.build(artist_params)
    if @artist.save
      redirect_target = (params[:artist][:from].presence || artists_path)
      redirect_to "#{redirect_target}?selected_artist_id=#{@artist.id}"
    else
      render 'new'
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_target = (params[:artist][:from].presence || artists_path)
      redirect_to "#{redirect_target}?selected_artist_id=#{@artist.id}"
    else
      render 'edit'
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  def favorites
    @favorite_artists = current_user.artists.where(favorited: true)
  end

  def toggle_favorite
    @artist.update!(favorited: !@artist.favorited)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_artist
    @artist = current_user.artists.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :nickname, :image, :genre, :memo, :nickname_mode, :favorited, :founding_date, :first_show_date, { members_attributes: [:id, :name, :_destroy] })
  end
end

app/views/artists/destroy.js.erb
$("#member_<%= @member.id %>").remove();

app/views/artists/edit.html.erb
<%= render "shared/artist_form", artist: @artist %>

app/views/artists/favorites.html.erb
<div class="main-container">
  <div class="artist-index">
    <div class="mb-4 d-flex justify-content-between">
      <%= link_to new_artist_path, class: "btn btn-success btn-lg mr-3" do %>
        <i class="fas fa-plus-circle"></i> 新規アーティスト作成
      <% end %>
      <%= link_to artists_path, class: "btn btn-info btn-lg" do %>
        全アーティスト一覧
      <% end %>
    </div>
    <div class="row">
      <% @favorite_artists.each do |artist| %>
        <div class="col-md-4">
          <div class="card mb-4 clickable" data-href="<%= artist_path(artist) %>">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                  <%= artist.combined_name %>
                </h5>
                <%= link_to "編集", edit_artist_path(artist), class: "btn btn-primary" %>
              </div>
              <div class="d-flex justify-content-between align-items-center mt-2">
                <p class="card-text mb-0">作成日: <%= artist.created_at.strftime("%Y-%m-%d") %></p>
                <%= link_to "削除", artist, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="main-container">
  <div class="artist-index">
    <div class="d-flex justify-content-between mb-3">
      <%= link_to new_artist_path, class: "btn btn-success mr-2" do %>
        <i class="fas fa-plus-circle"></i> 新規アーティスト作成
      <% end %>
      <%= link_to favorites_artists_path, class: "btn btn-info" do %>
        <i class="fas fa-heart"></i> お気に入り
      <% end %>
    </div>
    <div class="row">
      <% @artists.each do |artist| %>
        <div class="col-md-4">
          <div class="card mb-4 clickable" data-href="<%= artist_path(artist) %>">
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                  <%= artist.combined_name %>
                </h5>
                <%= link_to "編集", edit_artist_path(artist), class: "btn btn-primary btn-fixed-height" %>
              </div>
              <div class="d-flex justify-content-between align-items-center mt-2">
                <p class="card-text mb-0">作成日: <%= artist.created_at.strftime("%Y-%m-%d") %></p>
                <%= link_to "削除", artist, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/artists/new.html.erb
<%= render "shared/artist_form", artist: @artist %>

app/views/artists/show.html.erb
<div class="main-container">
  <div class="artist-show">
    <div class="d-flex justify-content-between mb-3">
      <div>
        <%= link_to edit_artist_path(@artist), class: "btn btn-primary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>
      <div>
        <%= link_to artist_path(@artist), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
    <div class="text-center mt-3 mb-3">
      <% if @artist.image.present? %>
        <%= image_tag(@artist.image.url, class: "image img-fluid") if @artist.image? %>
      <% end %>
    </div>
    <div class="artists-name text-center">
      <div class="d-inline-block align-middle mr-2 mb-3 display-4">
        <%= @artist.combined_name %>
      </div>
      <%= link_to toggle_favorite_artist_path(@artist), remote: true, method: :post do %>
        <% if @artist.favorited? %>
          <i class="fas fa-heart heart-pink align-middle"></i>
        <% else %>
          <i class="fas fa-heart heart-black align-middle"></i>
        <% end %>
      <% end %>
    </div>
    <% if @display_attributes["ジャンル"].present? %>
      <div class="mt-2 text-center h3">
        ジャンル:
        <%= @display_attributes["ジャンル"] %>
      </div>
    <% end %>
    <% if @display_attributes["結成日"].present? || @display_attributes["初ライブ日"].present? %>
      <div class="row mt-4 justify-content-center">
        <% if @display_attributes["結成日"].present? %>
          <div class="col-auto text-center h3">
            結成日:
            <%= @display_attributes["結成日"] %> (<%= days_since(@display_attributes["結成日"]) %>日目)
          </div>
        <% end %>
        <% if @display_attributes["初ライブ日"].present? %>
          <div class="col-auto text-center h3">
            初ライブ日:
            <%= @display_attributes["初ライブ日"] %> (<%= days_since(@display_attributes["初ライブ日"]) %>日目)
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="text-center mt-3">
      <% if @artist.members.any? %>
        <a class="text-lightgray h4" data-toggle="collapse" href="#membersList" role="button" aria-expanded="false" aria-controls="membersList">
          - メンバーを表示+ -
        </a>
      <% end %>
    </div>
    <div class="collapse" id="membersList">
      <div class="row mt-3">
        <% @artist.members.each_with_index do |member, index| %>
          <div class="col-4 text-center" id="member_<%= member.id %>">
            <p class="text-white">
              <%= member.name %>
              <%= link_to artist_member_path(@artist, member), method: :delete, remote: true, data: { confirm: "本当に削除しますか？" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </p>
          </div>
          <% if (index + 1) % 3 == 0 && (index + 1) != @artist.members.count %>
            </div>
            <div class="row">
          <% end %>
        <% end %>
      </div>
    </div>
    <% if @display_attributes["メモ"].present? %>
      <div class="mt-3 text-center h3">
        <h2>メモ</h2>
        <%= @display_attributes["メモ"] %>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/toggle_favorite.js.erb
<% if @artist.favorited? %>
  $(".fa-heart").removeClass("heart-black").addClass("heart-pink");
<% else %>
  $(".fa-heart").removeClass("heart-pink").addClass("heart-black");
<% end %>