config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'mypage', to: 'users#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :artists do
    collection do
      get :favorites
    end
    resources :members, only: [:index, :destroy]
    member do
      post 'toggle_favorite'
    end
  end
  resources :live_schedules do
    resources :venues, only: [:new, :create]
  end
  resources :live_records do
    get 'details', on: :member, format: :json
    resources :venues, only: [:new, :create]
  end
  resources :goods do
    resources :categories, only: [:new, :create]
  end
  get 'statistics', to: 'statistics#index'
  root 'home#index'
end

app/views/shared/_artist_form.html.erb
<div class="main-container">
  <div class="artist">
    <%= render "shared/error_messages", resource: artist %>
    <%= form_with model: artist do |f| %>
      <div class="d-flex justify-content-between align-items-end mb-1">
        <%= f.label :name, raw('アーティスト名 <span class="text-danger">*</span>'), class: "mb-0" %>
        <div class="col-3 d-flex align-items-center custom-checkbox label-checkbox-wrapper">
          <%= f.label :favorited, "お気に入り", class: "mb-0 flex-shrink-0 grey-label" %>
          <%= f.check_box :favorited %>
        </div>
      </div>
      <%= f.text_field :name, class: "form-control mb-3" %>
      <div class="d-flex justify-content-between align-items-center mb-1">
        <%= f.label :nickname, "ニックネーム", class: "mb-0" %>
        <div class="col-3 d-flex align-items-center custom-checkbox label-checkbox-wrapper">
          <%= f.label :nickname_mode, "ニックネーム表示", class: "mb-0 flex-shrink-0 grey-label" %>
          <%= f.check_box :nickname_mode %>
        </div>
      </div>
      <%= f.text_field :nickname, class: "form-control mb-3" %>
      <div class="form-group row mb-4">
        <div class="col d-flex flex-column align-items-center">
          <%= f.label :genre, "ジャンル", class: "mb-1" %>
          <%= f.select :genre, [["ジャンルを選択", ""], "ロック", "Jpop", "hiphop", "アイドル", "メタル", "ビジュアル系", "その他"], {}, class: "form-control" %>
        </div>
        <div class="col d-flex flex-column align-items-center">
          <%= f.label :founding_date, "結成日", class: "mb-1" %>
          <%= f.date_field :founding_date, class: "form-control" %>
        </div>
        <div class="col d-flex flex-column align-items-center">
          <%= f.label :first_show_date, "初ライブ日", class: "mb-1" %>
          <%= f.date_field :first_show_date, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="input-group">
          <input type="text" id="member-input" class="form-control" placeholder="メンバーの名前">
          <div class="input-group-append">
            <button type="button" id="add-member" class="btn btn-secondary">更に追加</button>
          </div>
        </div>
      </div>
      <div class="form-group text-center custom-file">
        <div class="label-box__inner">
          <label class="mealpicture">アーティスト画像を追加 <i class="fas fa-upload"></i>
              <%= f.file_field :image ,class:"input-default" %>
              <div class="boxFileSelect"></div>
          </label>
        </div>
      </div>
      <div class="form-group text-center mt-4">
        <%= f.label :memo, "メモ" %>
        <%= f.text_area :memo, class: "form-control memo" %>
      </div>
      <div class="form-group text-center">
        <%= f.hidden_field :from, value: params[:from] %>
        <%= f.submit "保存", class: "btn btn-primary w-50 mx-auto" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="text-center" id="error_explanation" data-turbo-cache="false">
    <p>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </p>
    <ul class="list-unstyled text-center">
      <% resource.errors.full_messages.each do |message| %>
        <li class="text-center"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_good_form.html.erb
<div class="main-container">
  <div class="good-form text-center">
    <div class="text-center display-4 mb-4">
      グッズ記録
    </div>
    <%= render "shared/error_messages", resource: good %>
    <%= form_with model: good do |f| %>
      <div class="form-row mb-2">
        <div class="form-group col-md-6">
          <%= f.label :quantity, "個数" %><span class="text-danger">*</span>
          <%= f.number_field :quantity, class: "form-control", placeholder: "数字を入力"  %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :カテゴリー %> <span class="text-danger">*</span>
          <%= f.select :category_id, categories.map { |c| [c.name, c.id] }, { include_blank: true, selected: @selected_category_id }, { class: "form-control text-center", id: "category_selector" } %>
        </div>
      </div>
      <div class="form-row justify-content-center mb-2">
        <div class="form-group col-md-4">
          <%= f.label :name, "商品名" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group col-md-4">
          <%= f.label :price, "価格" %>
          <%= f.number_field :price, class: "form-control", placeholder: "1つのグッズ価格を入力" %>
        </div>
        <%= f.fields_for :category do |cf| %>
          <div class="form-group col-md-4" id="new-categories" style="display:none">
            <%= cf.label :name, "- 追加するカテゴリーを入力 -" %>
            <%= text_field_tag "good[new_category_name]", nil, class: "form-control" %>
          </div>
        <% end %>
      </div>
      <div class="form-row mb-2">
        <div class="form-group col-md-4">
          <div class="text-center mb-2">
            <%= f.label :live_record_id, "ライブ記録" %>
          </div>
          <%= f.select :live_record_id, @live_records.map { |lr| [lr.name, lr.id] }, { include_blank: "-ライブ記録を選択-", selected: @good.live_record_id }, { class: "form-control text-center" } %>
        </div>
        <div class="form-group col-md-4">
          <div class="text-center mb-1">
            <%= f.label :artist_id, "アーティスト"%>
            <%= link_to "アーティストを追加", new_artist_path(from: request.fullpath), class: "btn btn-secondary btn-sm mb-1 " %>
          </div>
          <% selected_artist_id = params[:selected_artist_id] || "" %>
          <%= f.select :artist_id, current_user.artists.all.collect { |artist| [artist.display_name, artist.id] }, { include_blank: "-アーティストを選択-", selected: selected_artist_id }, class: "form-control text-center" %>
        </div>
        <div class="form-group col-md-4">
          <div class="text-center d-flex align-items-center justify-content-center mb-1">
            <%= f.label :member_id, "メンバー" %>
            <%= link_to "メンバーを追加", "#", class: "btn btn-secondary btn-sm mb-1 ml-2", id: "add_member_link", style: "display: none;" %>
          </div>
          <%= f.select :member_id, [["-アーティストを選択してください-", ""]], {}, { class: "form-control text-center", disabled: true, data: { selected_member_id: @good.member_id } } %>
        </div>
      </div>
      <div class="form-group mb-4">
        <%= f.label :date, "購入日", class: "text-center" %> <span class="text-muted">設定しない場合は記録作成日になります</span>
        <%= f.date_field :date, class: "form-control" %>
      </div>
      <%= f.submit "作成", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <%= link_to "Livehub", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "ライブ予定", live_schedules_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ライブ記録", live_records_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "グッズ記録", goods_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "統計", statistics_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to "マイページ", mypage_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to "登録アーティスト", artists_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-lg-none">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown d-none d-lg-block">
          <%= link_to current_user.username , "#", class: "nav-link dropdown-toggle", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false" %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= link_to "マイページ", mypage_path, class: "dropdown-item" %>
            <%= link_to "登録アーティスト", artists_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_live_record_form.html.erb
<div class="main-container">
  <div class="card">
    <div class="card-body">
      <div class="text-center display-4 mb-4">
        ライブ記録
      </div>
      <%= render "shared/error_messages", resource: live_record %>
      <%= form_with model: live_record do |f| %>
        <div class="form-row">
          <div class="form-group col-md-6 text-center">
            <%= f.label :name, "イベント名" %>
            <%= f.text_field :name, class: "form-control", placeholder: "入力しない場合は日付と会場のエリアになります" %>
          </div>
          <div class="form-group col-md-6">
            <div class="d-flex justify-content-between align-items-center text-center">
              <%= f.label :artist_id, "アーティスト" %>
              <%= link_to "新しいアーティストを追加", new_artist_path(from: request.fullpath), class: "btn btn-secondary btn-sm mb-1" %>
            </div>
            <%= f.select :artist_id, current_user.artists.all.collect { |artist| [artist.display_name, artist.id] }, { include_blank: "-アーティストを選択しない-", selected:  live_record.artist_id || "" }, class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6 text-center">
            <%= f.label :date, "日付" %> <span class="text-danger">*</span>
            <%= f.date_field :date, class: "form-control" %>
          </div>
          <div class="form-group col-md-6 text-center">
            <%= f.label :start_time, "START" %>
            <%= f.text_field :start_time, class: "timepicker", placeholder: "時間を選択可能" %>
          </div>
        </div>
        <%= f.fields_for :venue do |venue_fields| %>
          <div class="form-group text-center">
            <label for="venue-name-display">会場 <span class="text-danger">*</span></label>
            <input type="text" id="venue-name-display" class="form-control Autocomplete" placeholder="会場の名前を入力" value="<%= live_record.venue.name %>">
            <%= venue_fields.hidden_field :name, id: "nameField" %>
            <%= venue_fields.hidden_field :google_place_id, id: "google_place_idField" %>
            <%= venue_fields.hidden_field :area, id: "areaField" %>
            <%= venue_fields.hidden_field :latitude, id: "latitudeField" %>
            <%= venue_fields.hidden_field :longitude, id: "longitudeField" %>
          </div>
        <% end %>
        <div class="form-row">
          <div class="form-group col-md-6 text-center">
            <%= f.label :ticket_price, "チケット代" %>
            <%= f.number_field :ticket_price, class: "form-control", id: "ticket_price_input" %>
          </div>
          <div class="form-group col-md-6 text-center">
            <%= f.label :drink_price, "ドリンク代" %>
            <%= f.number_field :drink_price, class: "form-control",value: live_record.drink_price || 600 %>
          </div>
        </div>
        <div class="form-row liveimage text-center">
          <div class="label-box__inner">
              <label class="mealpicture">タイムテーブル画像を追加 <i class="fas fa-upload"></i>
                  <%= f.file_field :timetable ,class:"input-default" %>
                  <div class="boxFileSelect"></div>
                  <span id="timetable-filename"></span>
              </label>
          </div>
          <div class="label-box__inner">
              <label class="mealpicture">告知画像を追加 <i class="fas fa-upload"></i>
                  <%= f.file_field :announcement_image ,class:"input-default" %>
                  <div class="boxFileSelect"></div>
              </label>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.label :memo, "メモ" %>
          <%= f.text_area :memo, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "登録", class: "btn btn-dark btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_live_schedule_form.html.erb
<div class="main-container">
  <div class="card">
    <div class="card-body">
      <div class="text-center display-4">
        ライブ予定
      </div>
      <%= render "shared/error_messages", resource: live_schedule %>
      <%= form_with model: live_schedule do |f| %>
        <div class="form-row">
          <div class="form-group col-md-6 text-center">
            <%= f.label :name, "イベント名" %>
            <%= f.text_field :name, class: "form-control", placeholder: "入力しない場合は日付と会場のエリアになります" %>
          </div>
          <div class="form-group col-md-6">
            <div class="d-flex justify-content-between align-items-center text-center">
              <%= f.label :artist_id, "アーティスト" %>
              <%= link_to "新しいアーティストを追加", new_artist_path(from: request.fullpath), class: "btn btn-secondary btn-sm mb-1" %>
            </div>
            <%= f.select :artist_id, current_user.artists.all.collect { |artist| [artist.display_name, artist.id] }, { include_blank: "-アーティストを選択-", selected: live_schedule.artist_id || "" }, class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 text-center">
            <%= f.label :date, "日付" %> <span class="text-danger">*</span>
            <%= f.date_field :date, class: "form-control" %>
          </div>
          <div class="form-group col-md-4 text-center">
            <%= f.label :open_time, "OPEN" %>
            <%= f.text_field :open_time,  class: "timepicker", placeholder: "時間を選択可能" %>
          </div>
          <div class="form-group col-md-4 text-center">
            <%= f.label :start_time, "START" %>
            <%= f.text_field :start_time, class: "timepicker", placeholder: "時間を選択可能" %>
          </div>
        </div>
        <%= f.fields_for :venue do |venue_fields| %>
          <div class="form-group text-center">
            <label for="venue-name-display">会場 <span class="text-danger">*</span></label>
            <input type="text" id="venue-name-display" class="form-control Autocomplete" placeholder="会場の名前を入力" value="<%= live_schedule.venue.name %>">
            <%= venue_fields.hidden_field :name, id: "nameField" %>
            <%= venue_fields.hidden_field :google_place_id, id: "google_place_idField" %>
            <%= venue_fields.hidden_field :area, id: "areaField" %>
            <%= venue_fields.hidden_field :latitude, id: "latitudeField" %>
            <%= venue_fields.hidden_field :longitude, id: "longitudeField" %>
          </div>
        <% end %>
        <div class="form-group">
          <div class="ticket-status-label text-center">
            <%= f.label :ticket_status, "チケット購入状況" %>
          </div>
          <div class="btn-radio-group d-flex justify-content-around">
            <% LiveSchedule.ticket_statuses.keys.each do |status| %>
              <label class="btn-radio col-md-3">
                <%= f.radio_button :ticket_status, status, id: "ticket_status_#{status}", checked: @live_schedule.ticket_status == status %>
                <%= f.label "ticket_status_#{status}", status.humanize %>
              </label>
            <% end %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4 text-center">
            <%= f.label :ticket_sale_date, "チケット発売日時" %>
            <%= f.text_field :ticket_sale_date, class: "flatpickr", placeholder: "日時を選択可能" %>
          </div>
          <div class="form-group col-md-4 text-center">
            <%= f.label :ticket_price, "チケット代" %>
            <%= f.number_field :ticket_price, class: "form-control", id: "ticket_price_input" %>
          </div>
          <div class="form-group col-md-4 text-center">
            <%= f.label :drink_price, "ドリンク代" %>
            <%= f.number_field :drink_price, class: "form-control",value: @live_schedule.drink_price || 600 %>
          </div>
        </div>
        <div class="form-row liveimage text-center">
          <div class="label-box__inner">
              <label class="mealpicture">タイムテーブル画像を追加 <i class="fas fa-upload"></i>
                  <%= f.file_field :timetable ,class:"input-default" %>
                  <div class="boxFileSelect"></div>
              </label>
          </div>
          <div class="label-box__inner">
              <label class="mealpicture">告知画像を追加 <i class="fas fa-upload"></i>
                  <%= f.file_field :announcement_image ,class:"input-default" %>
                  <div class="boxFileSelect"></div>
              </label>
          </div>
        </div>
        <div class="form-group text-center">
          <%= f.label :memo, "メモ" %>
          <%= f.text_area :memo, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "登録", class: "btn btn-dark btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>