config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'mypage', to: 'users#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :artists do
    collection do
      get :favorites
    end
    resources :members, only: [:index, :destroy]
    member do
      post 'toggle_favorite'
    end
  end
  resources :live_schedules do
    resources :venues, only: [:new, :create]
  end
  resources :live_records do
    get 'details', on: :member, format: :json
    resources :venues, only: [:new, :create]
  end
  resources :goods do
    resources :categories, only: [:new, :create]
  end
  get 'statistics', to: 'statistics#index'
  root 'home#index'
end

app/models/live_schedule.rb
class LiveSchedule < ApplicationRecord
  belongs_to :artist, optional: true
  belongs_to :venue
  belongs_to :user
  accepts_nested_attributes_for :venue
  mount_uploader :timetable, AvatarUploader
  mount_uploader :announcement_image, AvatarUploader
  before_save :clear_ticket_sale_date_if_not_unpurchased
  validates :date, presence: true
  validate :ticket_sale_date_validation
  validates :ticket_price, numericality: { greater_than_or_equal_to: 0, message: "はマイナスの値を設定できません。", allow_blank: true }
  validates :drink_price, numericality: { greater_than_or_equal_to: 0, message: "はマイナスの値を設定できません。", allow_blank: true }
  validates :memo, length: { maximum: 300, message: "は300文字以内で入力してください。" }
  validate :date_cannot_be_in_the_past
  validate :start_time_after_open_time
  validate :ticket_sale_time_before_start_time_on_same_day

  enum ticket_status: {
    未購入: 0,
    購入済: 1,
    当日のみ: 2,
    チケ無し: 3
  }

  def ticket_sale_date_validation
    return if ticket_sale_date.blank?

    errors.add(:ticket_sale_date, "は作成日以降である必要があります。") if ticket_sale_date < Time.zone.today
    errors.add(:ticket_sale_date, "はライブの日付より後である必要があります。") if ticket_sale_date.to_date > date
  end

  def date_cannot_be_in_the_past
    return unless date.present? && date < Time.zone.today

    errors.add(:date, "は過去の日付を設定することはできません。")
  end

  def days_until_live
    return nil unless date

    (date - Time.zone.today).to_i
  end

  def clear_ticket_sale_date_if_not_unpurchased
    return unless ticket_status != "未購入"

    self.ticket_sale_date = nil
  end

  def start_time_after_open_time
    return if open_time.blank? || start_time.blank?

    return unless open_time > start_time

    errors.add(:start_time, "は開場時間よりも後である必要があります。")
  end

  def ticket_sale_time_before_start_time_on_same_day
    return if ticket_sale_date.blank? || start_time.blank?

    return unless ticket_sale_date.to_date == date && ticket_sale_date.strftime('%H:%M:%S') > start_time.strftime('%H:%M:%S')

    errors.add(:ticket_sale_date, "はライブの開始時刻よりも早く設定する必要があります。")
  end
end

app/controllers/live_schedules_controller.rb
class LiveSchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_live_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @live_schedules = current_user.live_schedules.where("date >= ?", Date.yesterday).order(:date)
  end

  def show
    @live_schedules = LiveSchedule.find(params[:id])
  end

  def new
    @live_schedule = LiveSchedule.new
    @live_schedule.ticket_status = "未購入"
    @live_schedule.build_venue
  end

  def edit
  end

  def create
    @live_schedule = current_user.live_schedules.build(live_schedule_params)

    venue_data = live_schedule_params[:venue_attributes]

    existing_venue = if venue_data[:google_place_id].present?
                       Venue.find_by(name: venue_data[:name], google_place_id: venue_data[:google_place_id], user_id: current_user.id)
                     else
                       Venue.find_by(name: venue_data[:name], user_id: current_user.id)
                     end

    if existing_venue
      @live_schedule.venue = existing_venue
    else
      venue = @live_schedule.build_venue(venue_data)
      venue.user = current_user
    end

    if @live_schedule.date.nil?
      @live_schedule.errors.add(:date, "を入力してください")
      render :new
      return
    end

    if @live_schedule.name.blank?
      date_str = @live_schedule.date.strftime("%-m月%-d日")
      @live_schedule.name = "#{date_str} #{@live_schedule.venue.area}"
    end

    if @live_schedule.save
      redirect_to live_schedules_path
    else
      Rails.logger.debug @live_schedule.errors.full_messages
      render :new
    end
  end

  def update
    @live_schedule = LiveSchedule.find(params[:id])

    venue_data = live_schedule_params[:venue_attributes]

    existing_venue = if venue_data[:google_place_id].present?
                       Venue.find_by(name: venue_data[:name], google_place_id: venue_data[:google_place_id], user_id: current_user.id)
                     else
                       Venue.find_by(name: venue_data[:name], user_id: current_user.id)
                     end

    if @live_schedule.name.blank?
      date_str = @live_schedule.date.strftime("%-m月%-d日")
      @live_schedule.name = "#{date_str} #{@live_schedule.venue.area}"
    end

    @live_schedule.assign_attributes(live_schedule_params)

    if existing_venue
      @live_schedule.venue = existing_venue
    else
      venue = @live_schedule.build_venue(venue_data.except(:user, :user_id))
      venue.user = current_user
      unless venue.save
        @live_schedule.errors.add(:venue, "の保存に失敗しました。")
        Rails.logger.debug venue.errors.full_messages
        render :edit and return
      end
    end

    if @live_schedule.save
      redirect_to live_schedules_path
    else
      Rails.logger.debug @live_schedule.errors.full_messages
      render :edit
    end
  end

  def destroy
    @live_schedule.destroy
    redirect_to live_schedules_path
  end

  private

  def set_live_schedule
    @live_schedule = current_user.live_schedules.find(params[:id])
  end

  def live_schedule_params
    params.require(:live_schedule).permit(:name, :date, :artist_id, :open_time, :start_time, :ticket_status, :ticket_sale_date, :ticket_price, :drink_price, :timetable, :announcement_image, :memo,
                                          venue_attributes: [:name, :google_place_id, :area, :latitude, :longitude])
  end
end

app/views/live_schedules/edit.html.erb
<%= render "shared/live_schedule_form", live_schedule: @live_schedule %>

app/views/live_schedules/index.html.erb
<div class="main-container d-flex flex-column align-items-center justify-content-start">
  <div class="container pt-4">
    <div class="row align-items-end">
      <div class="col-md-2 mb-2">
        <%= link_to "新規作成", new_live_schedule_path, class: "btn btn-success" %>
      </div>
      <div class="col-md-8 text-center mb-4">
        <div class="display-4 text-white">ライブ予定</div>
      </div>
      <div class="col-md-2">
      </div>
    </div>
    <div class="list-group">
      <% @live_schedules.each do |live_schedule| %>
        <a href="<%= live_schedule_path(live_schedule) %>" class="list-group-item list-group-item-action mb-2 d-flex flex-wrap align-items-center" style="background-color: white;">
          <div class="d-flex w-100 justify-content-between mb-2">
            <h5 class="mb-1"><%= live_schedule.name %></h5>
          </div>
          <div class="d-flex flex-wrap">
            <p class="mb-2 mr-3 flex-fill">
              <strong>日付:</strong> <%= l(live_schedule.date, format: "%-m月%-d日") %>
            </p>
            <% if live_schedule.artist.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>アーティスト:</strong> <%= live_schedule.artist.display_name %></p>
            <% end %>
            <p class="mb-2 mr-3 flex-fill">
              <strong>会場:</strong> <%= live_schedule.venue.name %>
              <% if live_schedule.venue.area.present? %>
                (<%= live_schedule.venue.area %>)
              <% end %>
            </p>
            <% if live_schedule.open_time.present? && live_schedule.start_time.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>OPEN:</strong> <%= live_schedule.open_time.strftime("%H:%M") %> <strong>START:</strong> <%= live_schedule.start_time.strftime("%H:%M") %></p>
            <% elsif live_schedule.open_time.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>OPEN:</strong> <%= live_schedule.open_time.strftime("%H:%M") %></p>
            <% elsif live_schedule.start_time.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>START:</strong> <%= live_schedule.start_time.strftime("%H:%M") %></p>
            <% end %>
            <p class="mb-2 mr-3 flex-fill"><strong>チケット:</strong> <%= live_schedule.ticket_status ? live_schedule.ticket_status.humanize : "未定" %></p>
            <p class="mb-2 mr-3 flex-fill"><strong>ライブまで:</strong> <%= live_schedule.days_until_live %>日</p>
            <% if live_schedule.ticket_price.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>チケット代:</strong> <%= live_schedule.ticket_price %>円</p>
            <% end %>
            <% if live_schedule.drink_price.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>ドリンク代:</strong> <%= live_schedule.drink_price %>円</p>
            <% end %>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/live_schedules/new.html.erb
<%= render "shared/live_schedule_form", live_schedule: @live_schedule %>

app/views/live_schedules/show.html.erb
<div class="main-container">
  <div class="card">
    <div class="card-body live-show">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
        <%= link_to edit_live_schedule_path(@live_schedule) do %>
          <i class="fas fa-edit"></i>
        <% end %>
        </div>
        <div class="text-center display-4">
          ライブ予定
        </div>
        <%= link_to @live_schedule, method: :delete, data: { confirm: "本当に削除しますか？" } do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
      <div class="text-center mb-2" id="weather-section" data-weather-api-key="<%= ENV["weather_API"] %>" data-latitude="<%= @live_schedule.venue.latitude %>" data-longitude="<%= @live_schedule.venue.longitude %>">
        <div id="weather-report-area"></div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 text-center">
          <label>イベント名</label>
          <p><%= @live_schedule.name %></p>
        </div>
        <% if @live_schedule.artist.present? %>
          <div class="form-group col-md-4 text-center">
            <label>アーティスト</label>
            <p><%= @live_schedule.artist.display_name %></p>
          </div>
        <% end %>
        <div class="form-group col-md-4 text-center">
          <label>会場</label>
          <p>
            <%= @live_schedule.venue.name %>
            <%= link_to "https://www.google.com/maps/search/#{@live_schedule.venue.name}", target: "_blank" do %>
              <i class="fas fa-map-marker-alt ml-2"></i>
            <% end %>
          </p>
        </div>
      </div>
      <div class="form-row d-flex justify-content-center">
        <div class="form-group col-md-4 text-center">
          <label>日付</label>
          <p id="live-schedule-date" data-date="<%= @live_schedule.date %>">
            <%= @live_schedule.date %>
          </p>
        </div>
        <% if @live_schedule.open_time? %>
          <div class="form-group col-md-4 text-center">
            <label>OPEN</label>
            <p><%= @live_schedule.open_time.strftime("%H:%M") %> </p>
          </div>
        <% end %>
        <% if @live_schedule.start_time? %>
          <div class="form-group col-md-4 text-center">
            <label>START</label>
            <p><%= @live_schedule.start_time.strftime("%H:%M") %></p>
          </div>
        <% end %>
        <div id="live-time-info" data-time="<%= @live_schedule.start_time ? @live_schedule.start_time.strftime("%H:%M") : (@live_schedule.open_time ? @live_schedule.open_time.strftime("%H:%M") : "12:00") %>"></div>
      </div>
      <% if @live_schedule.ticket_status? %>
        <div class="form-group text-center">
          <label>チケット購入状況</label>
          <p><%= @live_schedule.ticket_status.humanize %></p>
        </div>
      <% end %>
      <div class="form-row justify-content-center">
        <% if @live_schedule.ticket_sale_date? %>
          <div class="form-group col-md-4 text-center">
            <label>チケット発売日時</label>
            <p><%= @live_schedule.ticket_sale_date.strftime("%Y-%m-%d %H:%M") %></p>
          </div>
        <% end %>
        <% if @live_schedule.ticket_price? %>
          <div class="form-group col-md-4 text-center">
            <label>チケット代</label>
            <p><%= @live_schedule.ticket_price %></p>
          </div>
        <% end %>
        <% if @live_schedule.drink_price? %>
          <div class="form-group col-md-4 text-center">
            <label>ドリンク代</label>
            <p><%= @live_schedule.drink_price %></p>
          </div>
        <% end %>
      </div>
      <div class="form-row">
        <% if @live_schedule.timetable? %>
          <div class="form-group col-md-6 text-center">
            <label>タイムテーブル画像</label>
            <%= image_tag @live_schedule.timetable.url, size: "400x400", class: "img-fluid" %>
          </div>
        <% end %>
        <% if @live_schedule.announcement_image? %>
          <div class="form-group col-md-6 text-center">
            <label>告知画像</label>
            <%= image_tag @live_schedule.announcement_image.url, size: "400x400", class: "img-fluid" %>
          </div>
        <% end %>
      </div>
      <% if @live_schedule.memo? %>
        <div class="form-group text-center">
          <label>メモ</label>
          <p><%= @live_schedule.memo %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>