config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'mypage', to: 'users#show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :artists do
    collection do
      get :favorites
    end
    resources :members, only: [:index, :destroy]
    member do
      post 'toggle_favorite'
    end
  end
  resources :live_schedules do
    resources :venues, only: [:new, :create]
  end
  resources :live_records do
    get 'details', on: :member, format: :json
    resources :venues, only: [:new, :create]
  end
  resources :goods do
    resources :categories, only: [:new, :create]
  end
  get 'statistics', to: 'statistics#index'
  root 'home#index'
end

app/models/live_record.rb
class LiveRecord < ApplicationRecord
  has_many :goods, dependent: :nullify
  belongs_to :artist, optional: true
  belongs_to :venue
  belongs_to :user
  accepts_nested_attributes_for :venue
  mount_uploader :timetable, AvatarUploader
  mount_uploader :announcement_image, AvatarUploader
  validates :date, presence: true
  validates :ticket_price, numericality: { greater_than_or_equal_to: 0, message: "はマイナスの値を設定できません。", allow_blank: true }
  validates :drink_price, numericality: { greater_than_or_equal_to: 0, message: "はマイナスの値を設定できません。", allow_blank: true }
  validates :memo, length: { maximum: 300, message: "は300文字以内で入力してください。" }
  validate :date_cannot_be_in_the_future

  def date_cannot_be_in_the_future
    return unless date.present? && date > Time.zone.today

    errors.add(:date, "は未来の日付を設定することはできません。")
  end
end

app/controllers/live_records_controller.rb
class LiveRecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_live_record, only: [:show, :edit, :update, :destroy]

  def index
    @live_records = current_user.live_records.where("date <= ?", Time.zone.today).order(date: :desc)
  end

  def show
  end

  def new
    @live_record = LiveRecord.new
    @live_record.build_venue
  end

  def edit
 end

  def create
    @live_record = current_user.live_records.build(live_record_params)

    venue_data = live_record_params[:venue_attributes]

    existing_venue = if venue_data[:google_place_id].present?
                       Venue.find_by(name: venue_data[:name], google_place_id: venue_data[:google_place_id], user_id: current_user.id)
                     else
                       Venue.find_by(name: venue_data[:name], user_id: current_user.id)
                     end

    if existing_venue
      @live_record.venue = existing_venue
    else
      venue = @live_record.build_venue(venue_data)
      venue.user = current_user
    end

    if @live_record.date.nil?
      render :new
      return
    end

    if @live_record.name.blank?
      date_str = @live_record.date.strftime("%-m月%-d日")
      @live_record.name = "#{date_str} #{@live_record.venue.area}"
    end

    if @live_record.save
      redirect_to live_records_path
    else
      Rails.logger.debug @live_record.errors.full_messages
      render :new
    end
  end

  def update
    venue_data = live_record_params[:venue_attributes]

    existing_venue = if venue_data[:google_place_id].present?
                       Venue.find_by(name: venue_data[:name], google_place_id: venue_data[:google_place_id], user_id: current_user.id)
                     else
                       Venue.find_by(name: venue_data[:name], user_id: current_user.id)
                     end

    if @live_record.name.blank?
      date_str = @live_record.date.strftime("%-m月%-d日")
      @live_record.name = "#{date_str} #{@live_record.venue.area}"
    end

    @live_record.assign_attributes(live_record_params)

    if existing_venue
      @live_record.venue = existing_venue
    else
      venue = @live_record.build_venue(venue_data.except(:user, :user_id))
      venue.user = current_user
      unless venue.save
        @live_record.errors.add(:venue, "の保存に失敗しました。")
        Rails.logger.debug venue.errors.full_messages
        render :edit and return
      end
    end

    if @live_record.save
      redirect_to live_records_path
    else
      render :edit
    end
  end

  def destroy
    @live_record.destroy
    redirect_to live_records_path
  end

  def details
    live_record = LiveRecord.find(params[:id])
    render json: { date: live_record.date, artist: live_record.artist }
  end

  private

  def set_live_record
    @live_record = current_user.live_records.find(params[:id])
  end

  def live_record_params
    params.require(:live_record).permit(:name, :date, :artist_id, :start_time, :ticket_price, :drink_price, :timetable, :announcement_image, :memo,
                                        venue_attributes: [:name, :google_place_id, :area, :latitude, :longitude])
  end
end

app/views/live_records/edit.html.erb
<%= render "shared/live_record_form", live_record: @live_record %>

app/views/live_records/index.html.erb
<div class="main-container d-flex flex-column align-items-center justify-content-start">
  <div class="container pt-4">
    <div class="row align-items-end">
      <div class="col-md-2 mb-2">
        <%= link_to "新規作成", new_live_record_path, class: "btn btn-success" %>
      </div>
      <div class="col-md-8 text-center mb-4">
        <div class="display-4 text-white">ライブ記録</div>
      </div>
      <div class="col-md-2">
      </div>
    </div>
    <div class="list-group">
      <% @live_records.each do |live_record| %>
        <a href="<%= live_record_path(live_record) %>" class="list-group-item list-group-item-action mb-2 d-flex flex-wrap align-items-center" style="background-color: white;">
          <div class="d-flex w-100 justify-content-between mb-2">
            <h5 class="mb-1"><%= live_record.name %></h5>
          </div>
          <div class="d-flex flex-wrap">
            <p class="mb-2 mr-3 flex-fill">
              <strong>日付:</strong> <%= l(live_record.date, format: "%-m月%-d日") %>
            </p>
            <% if live_record.artist_id.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>アーティスト:</strong> <%= live_record.artist.display_name %></p>
            <% end %>
            <p class="mb-2 mr-3 flex-fill">
              <strong>会場:</strong> <%= Venue.find(live_record.venue_id).name %>
              <% if Venue.find(live_record.venue_id).area.present? %>
                (<%= Venue.find(live_record.venue_id).area %>)
              <% end %>
            </p>
            <% if live_record.ticket_price.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>チケット代:</strong> <%= live_record.ticket_price %>円</p>
            <% end %>
            <% if live_record.drink_price.present? %>
              <p class="mb-2 mr-3 flex-fill"><strong>ドリンク代:</strong> <%= live_record.drink_price %>円</p>
            <% end %>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/live_records/new.html.erb
<%= render "shared/live_record_form", live_record: @live_record %>

app/views/live_records/show.html.erb
<div class="main-container">
  <div class="card">
    <div class="card-body live-show">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
          <%= link_to edit_live_record_path(@live_record) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </div>
        <div class="text-center display-4">
          ライブ記録
          <%= link_to new_good_path(live_record_id: @live_record.id), class: "btn btn-primary mr-3 mb-2 d-block" do %>
            グッズ <i class="fas fa-plus"></i>
          <% end %>
        </div>
        <div>
          <%= link_to @live_record, method: :delete, data: { confirm: "本当に削除しますか？" } do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 text-center">
          <label>イベント名</label>
          <p><%= @live_record.name %></p>
        </div>
        <% if @live_record.artist_id.present? %>
          <div class="form-group col-md-4 text-center">
            <label>アーティスト</label>
            <p><%= @live_record.artist.display_name %></p>
          </div>
        <% end %>
        <div class="form-group col-md-4 text-center">
          <label>会場</label>
          <p>
            <%= Venue.find(@live_record.venue_id).name %>
            <%= link_to "https://www.google.com/maps/search/#{@live_record.venue.name}", target: "_blank" do %>
              <i class="fas fa-map-marker-alt ml-2"></i>
            <% end %>
          </p>
        </div>
        <div class="form-group col-md-4 text-center">
          <label>日付</label>
          <p><%= @live_record.date %></p>
        </div>
        <% if @live_record.start_time.present? %>
          <div class="form-group col-md-4 text-center">
            <label>START</label>
            <p><%= @live_record.start_time.strftime("%H:%M") %></p>
          </div>
        <% end %>
        <% if @live_record.ticket_price.present? %>
          <div class="form-group col-md-4 text-center">
            <label>チケット代</label>
            <p><%= @live_record.ticket_price %></p>
          </div>
        <% end %>
        <% if @live_record.drink_price.present? %>
          <div class="form-group col-md-4 text-center">
            <label>ドリンク代</label>
            <p><%= @live_record.drink_price %></p>
          </div>
        <% end %>
      </div>
      <div class="form-row">
        <% if @live_record.timetable.present? %>
          <div class="form-group col-md-6 text-center">
            <label>タイムテーブル画像</label>
            <%= image_tag @live_record.timetable.url, size: "400x400", class: "img-fluid" %>
          </div>
        <% end %>
        <% if @live_record.announcement_image.present? %>
          <div class="form-group col-md-6 text-center">
            <label>告知画像</label>
            <%= image_tag @live_record.announcement_image.url, size: "400x400", class: "img-fluid" %>
          </div>
        <% end %>
      </div>
      <% if @live_record.memo.present? %>
        <div class="form-group text-center">
          <label>メモ</label>
          <p><%= @live_record.memo %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>